NET-642 using execPROT on FTPSClients with Proxy Settings removes Pro…
apache/commons-net pull request #90
Opened 2021-10-22 08:00 UTC by YaniM

do not reset proxy settings when re-setting the socket factory
create method identical to open _openDataConnection_ for FTPS where proxy is used and ssl socket is created from ssl context

2021-10-30 06:44 UTC, YaniM commented
@garydgregory 
Hi, my idea for unit test is to set the proxy in FTPSClientTest.loginClient() and then execute client.connect(...) and PROT command but I'm not sure which hosts and ports to use?
For example in SocketClientFunctionalTest are defined hosts and ports but I cannot connect to them.

2022-04-05 04:40 UTC, sawantnitesh commented
Will it be merged. We are blocked because of this issue to migrate to Commons NET.

2022-04-05 13:29 UTC, garydgregory requested changes
Please see my comments.

2022-10-20 09:21 UTC, gremi64 commented
Hi, sooo... this PR allow to resolve a bug declared in 2017... but it's not merged because it lacks a unit test to fail without the main changes ?
Who would create a unit test with a socks proxy to prove it doesn't work as intended ?

I wonder if every fork are made to use this PR as i'll do.
Thanks @YaniM for the PR :heart:

2022-10-20 14:52 UTC, garydgregory commented
"i wonder why there is no test to prove it works in the first place"
Open source is no different than working in some companies, some people do work at different levels. I bet that if you did a git blame on that code, found the author, contacted them, you'd get some reply (maybe) like "it's too hard", "works for my setup", "I was busy" or any number of other reasons...

2022-11-07 15:20 UTC, merged

2023-07-30 13:52 UTC, pjfanning commented
@YaniM this PR seems to break FTPS proxy support for HTTP type proxies - see https://issues.apache.org/jira/browse/NET-718